# Generated by Django 4.0.3 on 2022-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=b'I01\n', default=None, max_length=50)),
                ('location_town', models.CharField(max_length=25)),
            ],
        ),
    ]
