# Generated by Django 4.0.3 on 2022-03-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='photo-gallery')),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(to='photos.category')),
                ('location', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='photos.location')),
            ],
        ),
    ]
