# Generated by Django 4.0.3 on 2022-03-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='photo_pic',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='date_upload',
            new_name='upload_date',
        ),
    ]
