# Generated by Django 4.0.3 on 2022-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_rename_photo_pic_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=None, max_length=30, null=b'I01\n'),
        ),
    ]
